# Generated by Django 4.2 on 2023-05-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deparment",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
