# Generated by Django 4.2 on 2023-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_deparment_name_alter_employee_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="doj",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
