# Generated by Django 4.2 on 2023-05-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_employee_doj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="doj",
            field=models.DateField(),
        ),
    ]
