# Generated by Django 4.2 on 2023-05-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_student_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="dob",
            field=models.DateTimeField(null=True),
        ),
    ]
